<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Accordion Block Template
 * @var $this Gene_BlueFoot_Block_Entity_Pagebuilder_Block_Default
 *
 */
$_entity = $this->getEntity();
?>
<?php if ($this->hasChildEntities('accordion_items')): ?>
    <?php $_collection = $this->getChildEntities('accordion_items'); ?>
    <div id="bluefoot-accordion-<?php echo $_entity->getId(); ?>" class="bluefoot-accordion bluefoot-full-width <?php echo $this->getCssAttributes(); ?>"<?php echo $this->getStyleAttributes(); ?>>
        <?php foreach ($_collection as $_block): ?>
            <?php echo $_block->toHtml(); ?>
        <?php endforeach; ?>
    </div>

    <script type="text/javascript">
        jQuery('#bluefoot-accordion-<?php echo $_entity->getId(); ?>').bluefootAccordion();
    </script>
<?php endif; ?>