<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Code Template
 * @var $this Gene_BlueFoot_Block_Entity_Pagebuilder_Block_Default
 *
 */
$_entity = $this->getEntity();
?>
<div id="bluefoot-code-<?php echo $_entity->getId(); ?>" class="bluefoot-code <?php echo $this->getCssAttributes(); ?>"<?php echo $this->getStyleAttributes(); ?>>
    <pre><code class="lineNumbers"><?php echo $_entity->getHtml(); ?></code></pre>
</div>
<script type="text/javascript">
    jQuery(function() {
        jQuery('#bluefoot-code-<?php echo $_entity->getId(); ?> code').each(function(i, block) {
            hljs.highlightBlock(block);
        });
    });
</script>