<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Content List Template
 * @var $this Gene_BlueFoot_Block_App_View
 *
 */

$_app = $this->getCurrentApp();

?>

<div class="page-title bluefoot-content-list-page-title">
    <h1><?php echo $_app->getTitle(); ?></h1>
</div>

<?php if ($_app->getViewOptions()->getShowDescription()) : ?>
    <div class="page-description bluefoot-content-list-page-description">
        <?php echo $_app->getDescription() ?>
    </div>
<?php endif; ?>