<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Image Template
 * @var $this Gene_BlueFoot_Block_Entity_PageBuilder_Block_Default
 *
 */
?>
<div class="gene-bluefoot-image gene-bluefoot-pagebuilder-block clearfix bluefoot-entity-align-{{ align }}">
    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'gene-bluefoot{{ image }}'; ?>" />
</div>
