<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Chloe Langford <chloe@gene.co.uk>
 *
 * Default List Template
 * @var $this Gene_BlueFoot_Block_App_View
 *
 */
$_entities = $this->getEntityCollection();
$_helper = Mage::helper('gene_bluefoot');
$_dateHelper = Mage::helper('gene_bluefoot/date');
$_imageHelper = Mage::helper('gene_bluefoot/image');

?>



<div class="bluefoot-content-list-content bluefoot-content-list-default">
    <?php if ($_entities->getSize()): ?>
        <div class="toolbar">
            <?php echo $this->getPagerHtml(); ?>
        </div>
        <div class="bluefoot-content-list-items<?php echo ($this->getGridView()) ? ' bluefoot-row' : ''; ?>">
            <?php $_i = 0; foreach ($_entities as $_entity): $_i++; ?>

                <?php if ($this->getGridView()): ?>

                    <div id="bluefoot-content-grid-item-<?php echo $_entity->getId(); ?>" class="bluefoot-content-grid-item bluefoot-column bluefoot-column-4<?php echo ($_i % 3 == 0) ? ' last' : '' ;?>">

                        <div class="bluefoot-fixed-height-item">
                            <?php if ($_image = $_entity->getFeaturedImage()): ?>
                                <a href="<?php echo $this->getEntityUrl($_entity); ?>" class="bluefoot-content-featured-image">
                                    <img src="<?php echo $_imageHelper->init($_image)->useConfig('thumbnail'); ?>" alt="<?php echo $_entity->getTitle(); ?>"/>
                                </a>
                            <?php endif; ?>

                            <h4 class="bluefoot-content-item-title">
                                <a href="<?php echo $this->getEntityUrl($_entity); ?>"><?php echo $_entity->getTitle(); ?></a>
                            </h4>

                            <?php if ($_date = $_entity->getPublishedDate()): ?>
                                <div class="bluefoot-content-meta">
                                    <p class="bluefoot-published-date"><?php echo $this->__('Published %s', $_dateHelper->getFriendlyDateTime(strtotime($_date))); ?></p>
                                </div>
                            <?php endif; ?>

                            <?php if ($_excerpt = $_entity->getExcerpt()): ?>
                                <div class="bluefoot-content-summary">
                                    <p><?php echo $_excerpt; ?></p>
                                </div>
                            <?php endif; ?>
                        </div>

                        <button type="button" onclick="location.href='<?php echo $this->getEntityUrl($_entity); ?>'" class="button bluefoot-read-more-link">
                            <span><span><?php echo $this->__('Continue Reading &raquo;'); ?></span></span>
                        </button>

                    </div>
                <?php else: ?>
                    <div id="bluefoot-content-list-item-<?php echo $_entity->getId(); ?>" class="bluefoot-content-list-item <?php echo ($_i == count($_entities)) ? ' last' : '' ;?>">

                        <?php if ($_image = $_entity->getFeaturedImage()): ?>
                            <a href="<?php echo $this->getEntityUrl($_entity); ?>" class="bluefoot-content-featured-image">
                                <img src="<?php echo $_imageHelper->init($_image)->useConfig('medium'); ?>" alt="<?php echo $_entity->getTitle(); ?>"/>
                            </a>
                        <?php endif; ?>

                        <h4 class="bluefoot-content-item-title">
                            <a href="<?php echo $this->getEntityUrl($_entity); ?>"><?php echo $_entity->getTitle(); ?></a>
                        </h4>

                        <?php if ($_date = $_entity->getPublishedDate()): ?>
                            <div class="bluefoot-content-meta">
                                <p class="bluefoot-published-date"><?php echo $this->__('Published %s', $_dateHelper->getFriendlyDateTime(strtotime($_date))); ?></p>
                            </div>
                        <?php endif; ?>

                        <?php if ($_excerpt = $_entity->getExcerpt()): ?>
                            <div class="bluefoot-content-summary">
                                <p><?php echo $_excerpt; ?></p>
                            </div>
                        <?php endif; ?>

                        <button type="button" onclick="location.href='<?php echo $this->getEntityUrl($_entity); ?>'" class="button bluefoot-read-more-link">
                            <span><span><?php echo $this->__('Continue Reading &raquo;'); ?></span></span>
                        </button>

                    </div>
                <?php endif; ?>

            <?php endforeach; ?>
        </div>
        <div class="toolbar-bottom">
            <div class="toolbar">
                <?php echo $this->getPagerHtml() ?>
            </div>
        </div>
        <script type="text/javascript">
            // Normalise heights
            jQuery(function(){
                jQuery('.bluefoot-content-list-content').bluefootNormaliseHeights({
                    block: '.bluefoot-fixed-height-item'
                });
            });
        </script>
    <?php else: ?>

        <div class="no-content bluefoot-no-content">
            <p><?php echo $this->__('There isn\'t any content yet'); ?></p>
        </div>

    <?php endif; ?>

</div>