<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Driver Template
 * @var $this Gene_BlueFoot_Block_Entity_Pagebuilder_Block_Default
 *
 */
$_entity = $this->getEntity();
$_helper = Mage::helper('gene_bluefoot');
?>

<a href="<?php echo $_entity->getLinkUrl(); ?>" id="bluefoot-driver-<?php echo $_entity->getId(); ?>" class="bluefoot-driver <?php echo $this->getCssAttributes(); ?>"<?php echo ($_entity->getTargetBlank())? ' target="_blank"' : '' ; ?><?php echo $this->getStyleAttributes(); ?>>
    <?php if ($_entity->getMobileImage()): ?>
        <img src="<?php echo $_helper->getImageUrl($_entity->getImage()); ?>"  alt="<?php echo $_entity->getAltTag(); ?>" title="<?php echo $_entity->getTitleTag(); ?>" class="bluefoot-mobile-hidden"/>
        <img src="<?php echo $_helper->getImageUrl($_entity->getMobileImage()); ?>"  alt="<?php echo $_entity->getAltTag(); ?>" title="<?php echo $_entity->getTitleTag(); ?>" class="bluefoot-mobile-only"/>
    <?php else: ?>
        <img src="<?php echo $_helper->getImageUrl($_entity->getImage()); ?>"  alt="<?php echo $_entity->getAltTag(); ?>" title="<?php echo $_entity->getTitleTag(); ?>" />
    <?php endif; ?>
    <?php if ($_text = $_entity->getLinkText()): ?>
        <span class="bluefoot-driver-text">
            <span><?php echo $_text; ?></span>
        </span>
    <?php endif; ?>
</a>