<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Image Template
 * @var $this Gene_BlueFoot_Block_Entity_Pagebuilder_Block_Default
 *
 */
$_entity = $this->getEntity();
$_helper = Mage::helper('gene_bluefoot');
?>
<figure id="bluefoot-image-<?php echo $_entity->getId(); ?>" class="bluefoot-image <?php echo $this->getCssAttributes(); ?>"<?php echo $this->getStyleAttributes(); ?>>
    <?php if ($_entity->getHasLightbox()): ?>
        <a href="<?php echo $_helper->getImageUrl($_entity->getImage()); ?>" class="bluefoot-lightbox" title="<?php echo $_entity->getTitleTag(); ?>">
    <?php endif; ?>
            <?php if ($_entity->getMobileImage()): ?>
                <img src="<?php echo $_helper->getImageUrl($_entity->getImage()); ?>"  alt="<?php echo $_entity->getAltTag(); ?>" title="<?php echo $_entity->getTitleTag(); ?>" class="bluefoot-mobile-hidden"/>
                <img src="<?php echo $_helper->getImageUrl($_entity->getMobileImage()); ?>"  alt="<?php echo $_entity->getAltTag(); ?>" title="<?php echo $_entity->getTitleTag(); ?>" class="bluefoot-mobile-only"/>
            <?php else: ?>
                <img src="<?php echo $_helper->getImageUrl($_entity->getImage()); ?>"  alt="<?php echo $_entity->getAltTag(); ?>" title="<?php echo $_entity->getTitleTag(); ?>" />
            <?php endif; ?>
        <?php if ($_entity->getHasLightbox()): ?>
        </a>
    <?php endif; ?>
    <?php if ($_entity->getShowCaption() && $_entity->getTitleTag()): ?>
        <figcaption>
            <?php echo $_entity->getTitleTag(); ?>
        </figcaption>
    <?php endif; ?>
</figure>

<?php if ($_entity->getHasLightbox()): ?>
    <script type="text/javascript">
        jQuery('#bluefoot-image-<?php echo $_entity->getId(); ?> .bluefoot-lightbox').fancybox({
            helpers: {
                overlay: {
                    locked: false
                }
            }
        });
    </script>
<?php endif; ?>