<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Shows all taxonomies assigned to the content that have been set to show.
 *
 * @var $this Gene_BlueFoot_Block_Entity_Content_View
 *
 */
$_entity = $this->getEntity();
$_taxonomies = $this->getEntityTaxonomies();
?>
<?php if ($_taxonomies): ?>
    <div class="bluefoot-content-view-taxonomies">
        <?php foreach($_taxonomies as $_taxonomy): ?>
            <?php $_terms = $this->getTaxonomyTerms($_taxonomy); ?>
            <?php if (($_terms && count($_terms))): ?>
                    <h4><?php echo $_taxonomy->getTitle(); ?></h4>
                    <ul class="bluefoot-content-view-taxonomy-list">
                        <?php $_i = 0; foreach($_terms as $_term): $_i++; ?>
                            <li><a href="<?php echo $_term->getTermUrl(); ?>"><?php echo $_term->getTitle(); ?></a></li>
                            <?php if ($_i < count($_terms)): ?>
                                <li class="bluefoot-list-divider">|</li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>
            <?php endif; ?>
            
        <?php endforeach; ?>
    </div>
<?php endif; ?>