<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Buttons Template
 * @var $this Gene_BlueFoot_Block_Entity_Pagebuilder_Block_Default
 *
 */
$_entity = $this->getEntity();
?>

<?php if ($this->hasChildEntities('button_items')): ?>

    <?php $_collection = $this->getChildEntities('button_items'); ?>
    <div class="bluefoot-buttons <?php echo $this->getCssAttributes(); ?>"<?php echo $this->getStyleAttributes(); ?>>
        <?php foreach ($_collection as $_block): ?>
            <?php echo $_block->toHtml(); ?>
        <?php endforeach; ?>
    </div>

<?php endif; ?>