<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Heading Template
 * @var $this Gene_BlueFoot_Block_Entity_Pagebuilder_Block_Heading
 *
 */
$_entity = $this->getEntity();
$_headingType = strtolower($this->getAttributeText('heading_type'));
?>

<<?php echo $_headingType; ?> class="<?php echo $this->getCssAttributes(); ?>"<?php echo $this->getStyleAttributes(); ?>><span><?php echo $this->escapeHtml($_entity->getTitle()); ?></span></<?php echo $_headingType; ?>>