<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Spacer Template
 * @var $this Gene_BlueFoot_Block_Entity_Pagebuilder_Block_Default
 *
 */
$_entity = $this->getEntity();
?>
<div class="bluefoot-spacer bluefoot-full-width <?php echo $this->getCssAttributes(); ?>"<?php echo ($_entity->getSpacerHeight()) ? ' style="height:' . $_entity->getSpacerHeight() . ';"': ''; ?><?php echo $this->getStyleAttributes(); ?>></div>