<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Full width row Template
 * @var $this Gene_BlueFoot_Block_Entity_Pagebuilder_Structural_Row
 *
 */
if ($this->getBackgroundStyles()):
    $this->setCssClasses('with-media-background');
endif;
?>
<div class="bluefoot-row <?php echo $this->getCssAttributes(); ?>"<?php echo $this->getStyleAttributes(); ?>>
    <?php echo $this->getRenderedChildHtml(); ?>
</div>