<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Accordion Item Template
 * @var $this Gene_BlueFoot_Block_Entity_PageBuilder_Block_Default
 *
 */
?>
<div class="bluefoot-accordion-outer gene-bluefoot-accordion-item bluefoot-entity-align-{{ align }}">
    <h4 class="bluefoot-accordion-link gene-bluefoot-accordion-item-heading no-edit">{{title}}</h4>
    <div class="bluefoot-accordion-inner gene-bluefoot-accordion-item-content" style="display: none;">
        {{{textarea}}}
    </div>
</div>